#!/bin/bash
# Script per calcular multipiples operacions
read -p "Ingresa el primer número: " num1
read -p "Ingresa el segon número: " num2
read -p "Ingresa la operació que vulguis realizar (+, -, / o *): " operacion

case $operacion in
  +)
    suma $num1 $num2
    ;;
  -)
    resta $num1 $num2
    ;;
  /)
    divisio $num1 $num2
    ;;
  X)
    multiplicacio $num1 $num2
    ;;
esac

